name: Create Actions Codepsace
on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        required: false

jobs:
  create_codepsace:
    env:
        GH_TOKEN: ${{ github.TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Create Codespace
        run: |
          gh auth status
          ${{ github.TOKEN }} >> tokenFile.txt
          gh auth login --with-token < tokenFile.txt
          gh auth status
          $codespace = $(gh cs create -r github/github)
          gh cs ssh -c $codespace
      - name: Start Services
        run: |
          service github start
          start-actions
      - run: |
          cd /workspaces/actions/actions-dotnet/src
          git checkout ${{ inputs.branch }}
          skyrise
          bm
          actions deploy -UseExistingDatabases
      - run: echo $codespace creation complete
    
