name: inherit_caller
on:
  workflow_dispatch:
jobs:
  call_in_repo:
    uses: ./.github/workflows/inherit_called.yml
    secrets: inherit
  call_public:
    uses: korea-dinos/nick-internal/.github/workflows/inherit_called.yml@main
    secrets: inherit
