name: main test
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hello world!'
  second_job:
    runs-on: ununtu-latest
    needs: [first_job]
    environment: production
    steps:
      - id: step 1
        run: echo 'deploy me!'
      - id: step 2
        run: |
          sleep 10
          echo 'I woke up!'
      - id: step 3
        run: echo 'marko!'
