name: main test
on: 
  workflow_dispatch:
jobs:
  call_job:
    uses: bbq-beets/nicholasbergesen/.github/workflows/callme.yml@main
  run_job:
    uses: bbq-beets/nicholasbergesen/.github/workflows/runme.yml@main
    
