name: main test
on: [workflow_run]
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hello world!'
  second_job:
    runs-on: ubuntu-latest
    needs: [first_job]
    environment: production
    steps:
      - run: echo 'deploy me!'
      - run: sleep 10
      - run: echo 'I woke up!'
      - run: echo 'marko!'
