name: Matrix-Caller
on:
  workflow_dispatch:
jobs:
  Reuseable:
    strategy:
        fail-fast: false
        matrix:
          include:
            - version: 1.x
            - version: 2.x
            
    uses: bbq-beets/nicholasbergesen/.github/workflows/matrix_called.yml@main
    with:
      version: ${{ matrix.version }}
    
