name: node_version_example

on: 
  workflow_dispatch:

jobs:
  node_version_job:
    strategy:
      matrix:
        node: [10, 12, 14]
    uses: bbq-beets/nicholasbergesen/.github/workflows/called.yml@main
      with:
        node-version: ${{ matrix.node }}
