name: Test Go
on:
  workflow_dispatch:
jobs:
  setup_go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v
      with:
        go-version: '^1.18.1' # The Go version to download (if necessary) and use.
    - run: go version
